# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0006_auto_20180524_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='tirle', max_length=200),
            preserve_default=False,
        ),
    ]
